# 图像进行简单的处理，主要是对于数据集中的图片进行处理

In [1]:
import torch
import numpy as np
import os
import  random
import cv2


print(torch.__version__)
arr = np.random.permutation(5)
print(arr)

1.7.1+cpu
[3 2 4 1 0]


In [9]:
np.random.permutation(arr)
print(np.random.permutation(5))

rendering_image = np.array([[1,2,3,4,5],[2,3,1,5,4]])
print(rendering_image)
for img_idx, img in enumerate(rendering_image):
    print(img_idx, img)
    rendering_image[img_idx] = img[..., arr]
    print(rendering_image)

[2 3 4 0 1]
[[1 2 3 4 5]
 [2 3 1 5 4]]
0 [1 2 3 4 5]
[[4 3 5 2 1]
 [2 3 1 5 4]]
1 [2 3 1 5 4]
[[4 3 5 2 1]
 [5 1 4 3 2]]


In [18]:
x = np.arange(10,1,-1)
print(x)
print(x[np.array([3, 3, 1, 8])])
x[np.array([[1,1],[2,3]])]





[10  9  8  7  6  5  4  3  2]
[7 7 9 2]


array([[9, 9],
       [8, 7]])